# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioshareX', '0002_remove_filesystem_archive_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='share',
            options={},
        ),
        migrations.AddField(
            model_name='share',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
