# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bioshareX', '0003_auto_20160607_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(blank=True, max_length=30, null=True)),
                ('text', models.CharField(blank=True, max_length=250, null=True)),
                ('paths', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='share',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sharelog',
            name='share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='bioshareX.Share'),
        ),
    ]
