# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 23:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bioshareX', '0004_auto_20160628_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
