# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioshareX', '0006_auto_20160804_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareftpuser',
            name='username',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
    ]
