# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 20:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bioshareX', '0009_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='viewed_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
