# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-12 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioshareX', '0011_share_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
