# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-13 18:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioshareX', '0013_auto_20161013_1147'),
    ]

    operations = [
        migrations.RunSQL(["INSERT INTO \"bioshareX_shareuserobjectpermission\"(permission_id,content_object_id,user_id) SELECT permission_id, object_pk, user_id FROM guardian_userobjectpermission;"]),
        migrations.RunSQL(["INSERT INTO \"bioshareX_sharegroupobjectpermission\"(permission_id,content_object_id,group_id) SELECT permission_id, object_pk, group_id FROM guardian_groupobjectpermission;"]),
    ]
