# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-13 18:47
from __future__ import unicode_literals

from django.db import migrations


def copy_guardian_permissions(apps, schema_editor):
    """
    One-time data migration that copied rows from the old generic guardian
    permission tables into the custom ShareUserObjectPermission /
    ShareGroupObjectPermission tables.

    On a fresh database (e.g. the test database) the guardian source tables
    may not exist yet, so the copy is skipped gracefully.

    We use a savepoint so that a missing-table error rolls back only to the
    savepoint rather than aborting the entire migration transaction (PostgreSQL
    leaves a transaction in a failed state after any error, preventing further
    SQL until an explicit rollback).
    """
    from django.db import transaction, utils
    try:
        with transaction.atomic(using=schema_editor.connection.alias):
            with schema_editor.connection.cursor() as cursor:
                cursor.execute(
                    'INSERT INTO "bioshareX_shareuserobjectpermission"'
                    '(permission_id,content_object_id,user_id) '
                    'SELECT permission_id, object_pk, user_id '
                    'FROM guardian_userobjectpermission'
                )
                cursor.execute(
                    'INSERT INTO "bioshareX_sharegroupobjectpermission"'
                    '(permission_id,content_object_id,group_id) '
                    'SELECT permission_id, object_pk, group_id '
                    'FROM guardian_groupobjectpermission'
                )
    except (utils.ProgrammingError, utils.OperationalError):
        # Source tables do not exist in fresh environments (e.g. test DB).
        # transaction.atomic() rolled back to the savepoint, so the outer
        # migration transaction is still healthy.
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('bioshareX', '0013_auto_20161013_1147'),
    ]

    operations = [
        migrations.RunPython(copy_guardian_permissions, migrations.RunPython.noop),
    ]
