# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-18 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioshareX', '0015_auto_20170323_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesystem',
            name='type',
            field=models.CharField(default=b'STANDARD', max_length=20),
        ),
    ]
