# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-18 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioshareX', '0016_filesystem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesystem',
            name='type',
            field=models.CharField(choices=[(b'STANDARD', b'Standard'), (b'ZFS', b'ZFS')], default=b'STANDARD', max_length=20),
        ),
    ]
