# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-07 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioshareX', '0017_auto_20170417_1734'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shareftpuser',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='shareftpuser',
            name='share',
        ),
        migrations.RemoveField(
            model_name='shareftpuser',
            name='user',
        ),
        migrations.AlterField(
            model_name='sharelog',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='ShareFTPUser',
        ),
    ]
