# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-16 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioshareX', '0018_auto_20170907_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelog',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
