# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-09 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioshareX', '0020_groupprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='last_data_access',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.Group'),
        ),
    ]
