# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-07 21:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioshareX', '0022_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepath',
            name='cluster',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='filepath',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='file_paths', to=settings.AUTH_USER_MODEL),
        ),
    ]
