# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-07 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bioshareX', '0023_auto_20210607_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='filepath',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bioshareX.FilePath'),
        ),
    ]
