# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-08 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioshareX', '0024_share_filepath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filepath',
            old_name='cluster',
            new_name='show_path',
        ),
    ]
