# Generated by Django 3.2.18 on 2023-04-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioshareX', '0026_auto_20230421_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='share',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='share',
            name='symlinks_found',
            field=models.DateTimeField(null=True),
        ),
    ]
